name: FFmpeg Nvenc Build and Upload Artifacts
on:
  push:
    #branches:
    #  - master
    #  - main
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      packages: write
    #
    strategy:
      matrix:
        ffmpeg: ["5.1.2", "6.0"]
        nvenc: ["11.0", "11.1"]
    #
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      #
      - name: Build FFmpeg ${{ matrix.ffmpeg }} Nvenc ${{ matrix.nvenc }}
        id: build-ffmpeg-nvenc
        shell: bash
        run: |
          sudo sh build.sh ${{ matrix.ffmpeg}} ${{ matrix.nvenc }}
      #
      - name: Upload FFmpeg ${{ matrix.ffmpeg }} Nvenc ${{ matrix.nvenc }}
        uses: actions/upload-artifact@v3
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
         name: upload-FFmpeg-${{ matrix.ffmpeg }}-Nvenc-${{ matrix.nvenc }}
         path: /tmp/bin/ffmpeg-ffprobe.tar
      #
      - name: Release FFmpeg ${{ matrix.ffmpeg }} Nvenc ${{ matrix.nvenc }}
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: "Release FFmpeg ${{ matrix.ffmpeg }} Nvenc ${{ matrix.nvenc }}"
          files: |
            LICENSE
            /tmp/bin/ffmpeg-ffprobe.tar
    #
  #
#
